// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEtSRHBfZpFhw0b2TfwZCa2D3qYFfHEjc',
    appId: '1:528151221706:web:74da8c1e4ebd090ea06b33',
    messagingSenderId: '528151221706',
    projectId: 'mercadinho-46ef1',
    authDomain: 'mercadinho-46ef1.firebaseapp.com',
    storageBucket: 'mercadinho-46ef1.appspot.com',
    measurementId: 'G-8KMBJJJQZ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArbeLYev9OvMjPZG0H4yGTSx4QV_H9d0Q',
    appId: '1:528151221706:android:38a6a03ee21f46bba06b33',
    messagingSenderId: '528151221706',
    projectId: 'mercadinho-46ef1',
    storageBucket: 'mercadinho-46ef1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnhzYU9ttihr5yZPkEcl7NPQHWhvrt1mo',
    appId: '1:528151221706:ios:2bcf02c14209b448a06b33',
    messagingSenderId: '528151221706',
    projectId: 'mercadinho-46ef1',
    storageBucket: 'mercadinho-46ef1.appspot.com',
    iosBundleId: 'com.example.mercadinho',
  );
}
